sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: lzx201708
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-take-out-felix
    access-key-secret: aih3RKwmzwJGoPM5w7iHypb32zHaIB
    access-key-id: LTAI5tE6zx9uRNcobFpn35uZ
  redis:
    host: localhost
    port: 6379
    password: lzx201708
    database: 10